###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mariadb:
        image: 'mariadb:10.8'
        working_dir: /application
        volumes:
            - './app:/application'
            - ./docker/database:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=FobomAppRootPassword
            - MYSQL_DATABASE=foreverdb
            - MYSQL_USER=azk
            - MYSQL_PASSWORD=FobomAzkPassword
        ports:
            - '49003:3306'

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.2.1
        restart: always
        ports:
            - "49002:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mariadb
            - UPLOAD_LIMIT=300M

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './app:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '49000:80'

    php-fpm:
        build: phpdocker/php-fpm
        container_name: fobom_php
        working_dir: /application
        volumes:
            - './app:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'
